# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "envimation/ubuntu-xenial"
  config.vm.box_url = "https://atlas.hashicorp.com/envimation/boxes/ubuntu-xenial"
  config.vm.hostname = "k8s"
  config.vm.synced_folder "k8s-manifests/elasticsearch", "/home/vagrant/elasticsearch"
  config.vm.network "forwarded_port", guest: 8080, host: 8087
  config.vm.provision "shell", inline: <<-SHELL
    echo "running scripts"
  SHELL
  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.provision :shell, :path => "scripts/install_docker.sh"
  config.vm.provision :shell, :path => "scripts/install_kubernetes.sh"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
end
