---
- name: setup commons
  hosts: all
  become: yes
  pre_tasks:
    - shell: echo starting
  roles:
    - { role: common, when: "ansible_os_family == 'Debian'" }
  post_tasks:
    - shell: echo ending
