# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
command -v curl &> /dev/null && EXIT_CODE=${?} || EXIT_CODE=${?}
if [ ${EXIT_CODE} == 1 ]
  then
    sudo apt update && sudo apt install curl -y
fi

curl https://raw.githubusercontent.com/ruanbekker/scripts/master/setup-node-exporter.sh | bash
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "shell", inline: $script

  config.vm.define "node1" do |node1|
    node1.vm.network "forwarded_port", guest: 9100, host: 9110
  end

  config.vm.define "node2" do |node2|
    node2.vm.network "forwarded_port", guest: 9100, host: 9120
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end
end
