# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "docker-mysql"
  config.vm.network "forwarded_port", guest: 3306, host: 3307
  #config.vm.network "private_network", ip: "10.10.0.201"
  config.vm.provision "docker" do |d|
    d.run "mysql", image: "mysql",
      args: "-p 3306:3306 -e MYSQL_ROOT_PASSWORD=password"
  end
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
end
